name: Automate CHANGELOG

on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g auto-changelog
#        run: |
#          git config --global user.email "saurav.1300@gmail.com"
#          git config --global user.name "sAuRaVsHARMAA"
      - name: Generate changelog
        run: |
          auto-changelog CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Automated changelog"
          git push origin main

