name: Automate CHANGELOG

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install github_changelog_generator
      - name: Generate changelog
        run: |
          github_changelog_generator --base CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Automated changelog"
          git push origin main
