name: Generate changelog

on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli
      - name: Generate changelog
        run: |
          conventional-changelog-cli -p changelog -i CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Automated changelog"
          git push origin main
